[build]
    command = "npm run build:prod"
    publish = "dist"
    functions = "lambda"

[environment]
    AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[dev]
    command = "npm run serve"
    port = 8888
    targetPort = 8080
    framework = "#custom"

[context.production.environment]
    LOG_ENDPOINT = "https://logger-test-81f86b.netlify.live/.netlify/functions/log"

[[redirects]]
    from = "/notes/*"
    to = "/.netlify/streamers/notes/:splat"
    status = 200
    force = true

[template.environment]
    PG_URI = "Your postgress connection URI"